### ISSUE TITLE
Shell题目提交时，solution文件中只含有leetcode的预设文字

### ISSUE THREAD

**Issue by latte-z** [binarylu/leetcode-ext#1]
比如shell195题，commit的solution文件只有 ”# Read from the file file.txt and output the tenth line to stdout.“ 一行内容，更改文件名重新提交也无法解决这个问题~

顺便感谢下你做的这个插件~~

**Comment by binarylu** [comment]
我试了下没问题。麻烦你在这个题目的页面打开chrome的开发者工具里的console，然后输入  $('#code_content').val()          看打印出来的是不是正确的内容。提交代码的时候就是从这里取代码内容的，页面加载完和更改select都会更改这个id对应的元素里的内容。

**Comment by latte-z** [comment]
$('#code_content').val() 能正确获取到内容，于是我删掉两个旧文件重新submit一次后居然又有了...好神奇....

谢谢回复，请关闭这个issues

**Comment by binarylu** [comment]
再遇到问题就刷新页面尝试下。感谢

**Comment by binarylu** [comment]
@latte-z 不好意思，确实是个bug，只会在第一次提交的时候才抓取code内容，之后的内容都是第一次抓取的。已经修复bug了，插件会自动更新

**Comment by latte-z** [comment]
@binarylu get✓谢谢
