### ISSUE TITLE
Is it possible to install this extension to Chrome from source code directly?

### ISSUE THREAD

**Issue by zhaodelong** [binarylu/leetcode-ext#10]
I just found the extension disappeared from my chrome. I came here and noticed the announcement. I really like this extension for my daily leetcode practices. I'm wondering if it's possible to install it on my chrome from source code directly?

Really appreciate your contribution and totally understand your time limitation. 

Thanks first. :)

**Comment by binarylu** [comment]
Thank you for loving my extension. The answer of your question is YES. You can import extension code by enable chrome developer mode in chrome://extensions, and click "load unpacked  extension", load leetcode-ext folder
