### ISSUE TITLE
无法为内容脚本加载 JavaScript“config.js”

### ISSUE THREAD

**Issue by jimmyyao** [binarylu/leetcode-ext#11]
下载zip package， 解压之后加载到chrome， 出现以上的问题。
用js lint查了下config.js 没有问题，是其他什么问题吗？

**Comment by tankztc** [comment]
leetcode-ext里有个config-sample.js， 你把它改成你自己的应该就可以了

**Comment by binarylu** [comment]
楼上正解。自己到github申请client id和client secret，然后用server文件夹里的代码部署到自己服务器，即可使用完整功能。最近正在重构，改成无服务器版本，欢迎提建议
