### ISSUE TITLE
Company tag跟加锁题都看不了了

### ISSUE THREAD

**Issue by tankztc** [binarylu/leetcode-ext#12]
之前company tags跟加锁题都能看，今天发现company tags 跟加锁题都看不了了

**Comment by binarylu** [comment]
服务器未续费停机了，因为之前leetcode发邮件说我侵权，就不打算再续费服务器了，现在正在开发无服务器版本（仍然支持所有功能），避免侵权问题。请耐心等待新的版本发布，感谢支持
