### ISSUE TITLE
The tag bar is totally broken :'((((

### ISSUE THREAD

**Issue by Juan555** [binarylu/leetcode-ext#14]
Everything in tag bar is 0/0, and I can't even see the category after I updated my account to see locked questions. Plz heeeelp. Career fair is next week. :'((((((

**Comment by binarylu** [comment]
Sorry for the inconvenience, but leetcode.com has threaten for my sharing locked problem. I'm working on the new version to get rid of legal issue. It may take me 2 - 3 more weeks to get enough time. I would suggest you to search the locked problem online, many of which are shared by the others. If you really care about you career fair next week, you can purchase leetcode premium for one month, it is worthy. BTW, good luck with your job seeking.

**Comment by Juan555** [comment]
Hi, thank you for your time and patience! I think I didn't state my problem
clearly. I've already purchased leetcode premium, and after that, all the
tags become 0/0 and I cannot see my progress in company and tag any more.
But thank you for all the effort! Let me know whether I state the problem
clearly this time. :)

Best,
Huan
