### ISSUE TITLE
Sorry that I didn't state my problem clearly last time

### ISSUE THREAD

**Issue by Juan555** [binarylu/leetcode-ext#15]
Hi, thank you for your time and patience! I think I didn't state my problem clearly. I've already purchased leetcode premium, and after that, all the tags become 0/0 and I cannot see my progress in company and tag any more. But thank you for all the effort! Let me know whether I state the problem clearly this time. :)

Best,
Huan

**Comment by Juan555** [comment]
and I believe it's a problem even though I'm not logged in. :o

**Comment by Juan555** [comment]
![screen shot 2016-09-05 at 11 42 37 am](https://cloud.githubusercontent.com/assets/16981201/18253865/e575c5d0-735d-11e6-8943-1c38c3eb4365.png)

**Comment by binarylu** [comment]
Please **DISABLE** this extension for now. The current extension in your chrome has not been maintained for a long time, there are a lot of hidden issue.

**Comment by Juan555** [comment]
Could I know the link to the new version of extension? I can't find it for some reason. :(
