### ISSUE TITLE
why the extension does not exist in the chrome extension store

### ISSUE THREAD

**Issue by Nicksxs** [binarylu/leetcode-ext#17]
and whether could you release a compiled zip package for me to use, thanks.  forgive my poor english

**Comment by binarylu** [comment]
No need to compile or compress. You can use chrome to load directly. Type "chrome://extension", check "Developer mode" and then you will see a button named "load unpacked extension..".

**Comment by Nicksxs** [comment]
i tried last night,but found that i cannot login github account and get the repository and push the code

**Comment by binarylu** [comment]
Register a github application at [here](https://github.com/settings/developers) to get client_id and secret. Then modify the value of `client_id` and `client_secret` in [this file](https://github.com/binarylu/leetcode-ext/blob/master/leetcode-ext/config-sample.js) and rename filename as instructed in the comment.

**Comment by Nicksxs** [comment]
i register a application but only got a token,what is the client_id and secret

**Comment by binarylu** [comment]
open your github setting page and click "OAuth applications" on the left-bottom

**Comment by Nicksxs** [comment]
does this mean i need to run a server application?
