### ISSUE TITLE
 Hide locked problems feature

### ISSUE THREAD

**Issue by erlizhou** [binarylu/leetcode-ext#4]
Thanks for your great project! Although I have a suggestion: it looks like the Hide locked problems feature is broken after the latest update. It is showing "You have solved NaN / NaN problems" and hiding all problems if you tick that box.

**Comment by oio14644** [comment]
求修复hide 功能

**Comment by binarylu** [comment]
I will fix it today. Thank you.

**Comment by binarylu** [comment]
I have fixed this bug, thank you both.
