### ISSUE TITLE
Suggestion about Multiple solutions

### ISSUE THREAD

**Issue by ws93** [binarylu/leetcode-ext#7]
Hi, I've been using this Leetcode extension for days and it's pretty nice and convenient. But there is an issue when I have some different solutions for one problem. 

Since the default name of solution is Solution.java(actually it's solution.java, but I think you can change that to uppercase since the default public class is Solution), when I have a new solution for this problem, the new commit will overwrite the old Solution.java. So it just shows the newest one instead of all of my submissions.

So I think that every time we submit a solution, no matter it's AC or TLE or something wrong, this extension could create a new file in our repo with a different name like Solution1.java, Solution2.java. In this case we can keep all our solutions instead of the newest one.

This extension is pretty awesome! Thank you again for sharing!

**Comment by ws93** [comment]
Oh sorry. I just realized that I can change the name and comment for each different solution!

**Comment by binarylu** [comment]
Thank you for your comments.
Yes, you can change the filename. And you can also set to commit only AC or others.
